name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - master
    - develop
  tags:
    include:
      - v*
  paths:
    exclude:
    - '*.md'

pr:
  branches:
    include:
    - develop
    - master
    - release/*
  paths:
    exclude:
    - '*.md'

resources:
  repositories:
    - repository: templates
      type: github
      name: CluedIn-io/AzurePipelines.Templates
      endpoint: 'CluedIn-io'

pool:
  vmImage: 'windows-latest'

variables:
  - group: nuget
  - name: testFolderPath
    value: '$(Build.SourcesDirectory)/test'
  - name: dotnet.skip.first.time.experience
    value: 'true'

steps:
- powershell: |
    @('develop','release','AzurePipelines') | ForEach-Object{
      nuget sources update -Name $_ -Password $env:NUGET_KEY -UserName VssSessionToken -ConfigFile nuget.config
    }
  condition: and(succeeded(), variables['nuget.key'])
  displayName: 'Add api token to access nuget artifacts'
  env:
    NUGET_KEY: $(nuget.key)
    
- template: crawler.default.build.yml@templates

- template: documentation.publish.yml@templates